name:                bad-monaderror
version:             0.0.0.0
license:             AllRightsReserved
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2019 Cary Robbins"

dependencies:
- base
- postgresql-query
- mtl
- monad-logger
- exceptions

executables:
  bad-monaderror:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
